### ISSUE TITLE
The code has a lot of warnings

### ISSUE THREAD

**Issue by arturocs** [pepitoenpeligro/CloudBanking#52]

**Comment by pepitoenpeligro** [comment]
Most of the warnings are generated due to the existence of empty functions, and not use of `snake_case`. I hope to be able to change it for the next MVP (0.3.0). Meanwhile, I'm working on it.
![Captura de pantalla 2020-11-12 a las 13 10 43](https://user-images.githubusercontent.com/14912971/98938659-86f2be00-24e8-11eb-9a6f-66a9bf7f1d92.png)

Thank you very much for letting me know.

**Comment by arturocs** [comment]
Running cargo clippy gives you more warnings that usually aren't shown

**Comment by pepitoenpeligro** [comment]
Thank you very much @arturocs !
